services:
  app:
    build: .
    ports:
      - "${HOST_PORT:-5000}:5000"                  # Host port from env var, default 5000
    environment:
      - CONTAINER_PORT=5000                        # Container port
      - HOST_PORT=${HOST_PORT}                     # Host port
      - PYTHONUNBUFFERED=1
      - DEBUG=${DEBUG}
      - AUTH_USERNAME=${AUTH_USERNAME}             # Login
      - AUTH_PASSWORD=${AUTH_PASSWORD}             # Plain text password
      - TOKEN_EXPIRE_HOURS=${TOKEN_EXPIRE_HOURS}   # Optional
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}           # Optional
    volumes:
      - ~/Media/music:/music                       # Library